name = "adatudes"
description = "Shiny new project"
version = "0.0.0"

authors = ["Anuj Seth"]
maintainers = ["Anuj Seth <anujseth76@gmail.com>"]
maintainers-logins = ["anuj-seth"]

executables = ["adatudes"]
